spring.application.name=demo

spring.datasource.url=jdbc:mysql://localhost:3306/controle_cotacao_aviacao
spring.datasource.username=root
spring.datasource.password=Pedrobarao@100
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true