spring.application.name=demo_remake

spring.datasource.url=jdbc:mysql://localhost:3306/controle_cotacao_aviacao_remake
spring.datasource.username=root_remake
spring.datasource.password=Pedrobarao@100
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

spring.jackson.date-format=dd/MM/yyyy HH:mm:ss